Repository Kim-Dong-Hyeon/KickBoardApp, pull requests merged in 2024-07, with the labels that each got.

#11 지도 화면 구현 및 현재 위치 마커 구현
  KickBoard+CoreDataClass.swift
  KickBoard+CoreDataProperties.swift
  KickBoardApp.xcodeproj/project.pbxproj
  KickBoardApp/AppDelegate.swift
  KickBoardApp/Assets.xcassets/current_location_marker.imageset/Contents.json
  KickBoardApp/Assets.xcassets/current_location_marker.imageset/current_location_marker.png
  KickBoardApp/Controller/HomeController.swift
  KickBoardApp/Controller/MapController.swift
  KickBoardApp/Controller/TabBarContorller.swift
  KickBoardApp/Controller/UserProfiles/RegisterHistory.swift
  KickBoardApp/Info.plist
  KickBoardApp/KickBoardApp.xcdatamodeld/KickBoardApp.xcdatamodel/contents
  KickBoardApp/Model/LocationManager.swift
  KickBoardApp/View/HomeView.swift
  KickBoardApp/View/MapView.swift
Labels: enhancement

#12 Fix: Git Conflict 해결 commit
  KickBoardApp.xcodeproj/project.pbxproj
  KickBoardApp/Controller/TabBarContorller.swift
  KickBoardApp/Controller/UserProfiles/MypageController.swift
  KickBoardApp/Info.plist
  KickBoardApp/KickBoardApp.xcdatamodeld/KickBoardApp.xcdatamodel/contents
  KickBoardApp/Model/KickBoard+CoreDataClass.swift
  KickBoardApp/Model/KickBoard+CoreDataProperties.swift
Labels: bug

#14 Feat: 사진 추가 기능, Fix: UI수정
  KickBoardApp/Controller/RegisterKickboardController.swift
  KickBoardApp/View/RegisterKickboardView.swift
Labels: enhancement

#16 Feat: 셀꾸미기
  KickBoardApp.xcodeproj/project.pbxproj
  KickBoardApp/Controller/UserProfiles/RegisterHistoryController.swift
  KickBoardApp/Controller/UserProfiles/UsageHistoryController.swift
  KickBoardApp/View/UserProfiles/RegisterCell.swift
  KickBoardApp/View/UserProfiles/RegisterHistoryView.swift
Labels: enhancement

#18 Fix: Git Conflict 해결 commit
  KickBoardApp.xcodeproj/project.pbxproj
  KickBoardApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KickBoardApp/View/HomeView.swift
Labels: bug

#19 Feat: DataManager
  KickBoardApp.xcodeproj/project.pbxproj
  KickBoardApp/Controller/UserProfiles/MypageController.swift
  KickBoardApp/Model/DataManager.swift
  KickBoardApp/View/UserProfiles/MyPageView.swift
Labels: enhancement

#23 Feat: Map API 재사용
  KickBoardApp/Assets.xcassets/track_location_btn.imageset/Contents.json
  KickBoardApp/Assets.xcassets/track_location_btn.imageset/track_location_btn.png
  KickBoardApp/Controller/HomeController.swift
  KickBoardApp/Controller/MapController.swift
  KickBoardApp/Controller/RegisterKickboardController.swift
  KickBoardApp/Controller/TabBarContorller.swift
  KickBoardApp/KickBoardApp.xcdatamodeld/KickBoardApp.xcdatamodel/contents
  KickBoardApp/View/MapView.swift
  KickBoardApp/View/RegisterKickboardView.swift
Labels: enhancement

#35 Revert "Cg"
  KickBoardApp/Controller/HomeController.swift
  KickBoardApp/Controller/LoginController.swift
  KickBoardApp/Controller/MapController.swift
  KickBoardApp/Controller/RegisterKickboardController.swift
  KickBoardApp/Controller/UserProfiles/MypageController.swift
  KickBoardApp/Controller/UserProfiles/RegisterHistoryController.swift
  KickBoardApp/KickBoardApp.xcdatamodeld/KickBoardApp.xcdatamodel/contents
  KickBoardApp/Model/DataManager.swift
  KickBoardApp/Model/KickBoard+CoreDataClass.swift
  KickBoardApp/Model/KickBoard+CoreDataProperties.swift
  KickBoardApp/SceneDelegate.swift
  KickBoardApp/View/RegisterKickboardView.swift
  KickBoardApp/View/UserProfiles/MyPageView.swift
Labels: bug

#47 Fix: currentLocationButton 이동(Map -> Home)
  KickBoardApp.xcodeproj/project.pbxproj
  KickBoardApp/AppDelegate.swift
  KickBoardApp/Assets.xcassets/track_location_btn.imageset/Contents.json
  KickBoardApp/Controller/HomeController.swift
  KickBoardApp/Controller/MapController.swift
  KickBoardApp/Controller/RegisterKickboardController.swift
  KickBoardApp/Controller/TabBarContorller.swift
  KickBoardApp/Info.plist
  KickBoardApp/Model/LocationManager.swift
  KickBoardApp/View/HomeView.swift
  KickBoardApp/View/MapView.swift
  KickBoardApp/View/UserProfiles/RegisterCell.swift
Labels: bug

#64 Kdh to develop PR
  KickBoardApp.xcodeproj/project.pbxproj
  KickBoardApp/Controller/HomeController.swift
  KickBoardApp/Controller/MapController.swift
  KickBoardApp/Controller/RegisterKickboardController.swift
  KickBoardApp/Controller/TabBarContorller.swift
  KickBoardApp/Info.plist
  KickBoardApp/Model/AddressFetcher.swift
  KickBoardApp/Model/DataManager.swift
  KickBoardApp/Model/LocationManager.swift
  KickBoardApp/Model/RegionFetcher.swift
  KickBoardApp/View/HomeView.swift
  KickBoardApp/View/MapView.swift
  KickBoardApp/View/RegisterKickboardView.swift
Labels: bug, enhancement
